<?php
    require 'PHPMailer/PHPMailerAutoload.php';

    $name=$_POST["name"];
    $lastName=$_POST["lastName"];
    $email=$_POST["email"];
    $subject=$_POST["subject"];
    $message=$_POST["message"];

    $mail=new PHPMailer;

    //$mail->SMTPDebug=true;

    $mail->isSMTP();                            // Set mailer to use SMTP
    $mail->Host='mail.nucliux.mx';              // Specify main and backup SMTP servers
    $mail->SMTPAuth=true;                       // Enable SMTP authentication
    $mail->Username='contacto@nucliux.mx';      // SMTP username
    $mail->Password='XV8-*8!Z';               // SMTP password

    $mail->CharSet='UTF-8';
    $mail->setFrom('contact@glacierjeans.com', 'The Glacier Jeans Factory Web Site');
    $mail->addAddress('contact@glacierjeans.com', 'The Glacier Jeans Factory');
    $mail->Subject='Someone send a message from the web site';

    $mensaje_correo="This is an autogenerated mail from The Glacier Jeans Factory web site.<br><br>";
    $mensaje_correo.="Name: ".$name."<br>";
    $mensaje_correo.="Last name: ".$lastName."<br>";
    $mensaje_correo.="Email: ".$email."<br>";
    $mensaje_correo.="Subject: ".$subject."<br>";
    $mensaje_correo.="Message: ".$message."<br>";

    $mail->msgHTML($mensaje_correo);
         
    if(!$mail->send())
        echo ("Mailer Error: ".$mail->ErrorInfo);
    else 
        echo true;
?>